# Generated by Django 5.0.2 on 2024-03-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipe_author_recipe_createdon_recipe_updatedon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
